const mongoose = require('mongoose');

const inventorySchema = new mongoose.Schema(
  {
    enterpriseSupplier: { type: String, default: '' },
    totalQuantityOnHand: { type: Number, default: null },
    totalQuantityOnPurchaseOrder: { type: Number, default: null },
    totalWeeksOnHand: { type: Number, default: null },
    totalWeeksOnPO: { type: Number, default: null },
    totalQuantityOnSalesOrder: { type: Number, default: null },
    brand: { type: String, default: '' },
    brandTotalQuantityOnHand: { type: Number, default: null },
    brandTotalQuantityOnPurchaseOrder: { type: Number, default: null },
    brandTotalWeeksOnHand: { type: Number, default: null },
    brandTotalWeeksOnPO: { type: Number, default: null },
    brandTotalQuantityOnSalesOrder: { type: Number, default: null },
    dc: { type: String, default: '' },
    dcTotalQuantityOnHand: { type: Number, default: null },
    dcTotalQuantityOnPurchaseOrder: { type: Number, default: null },
    dcTotalWeeksOnHand: { type: Number, default: null },
    dcTotalWeeksOnPO: { type: Number, default: null },
    dcTotalQuantityOnSalesOrder: { type: Number, default: null },
    textbox31: { type: String, default: '' },
    upc: { type: String, default: '' },
    productDescription: { type: String, default: '' },
    vendorCasePack: { type: Number, default: null },
    quantityOnHand: { type: Number, default: null },
    quantityOnPurchaseOrder: { type: Number, default: null },
    weeksOnHand: { type: Number, default: null },
    weeksOnPO: { type: Number, default: null },
    quantityOnSalesOrder: { type: Number, default: null },
    downloadedOn: { type: String, default: '' },
    reportMonth: { type: String, default: '' },
    sku: { type: String, default: '' },
    boxPerCase: { type: Number, default: null },
    material: { type: String, default: '' },
    productCategory: { type: String, default: '' },
    productSubCategory: { type: String, default: '' },
    productType: { type: String, default: '' },
    esn: { type: String, default: '' },
    supplier: { type: String, default: '' },
    broker: { type: String, default: '' },
    itemDescription: { type: String, default: '' },
    reason: { type: String, default: '' },
    note: { type: String, default: '' },
    pack: { type: String, default: '' },
    size: { type: String, default: '' },
    uom: { type: String, default: '' },
    guaranteedShelfLifeDaysToCustomer: { type: Number, default: null },
    sellByDate: { type: String, default: '' },
    daysRemainingToShipToCustomer: { type: Number, default: null },
    unitSalesVelocityPerDay: { type: Number, default: null },
    unitsOnHandWithNoForecastDemand: { type: Number, default: null },
    inventoryAgeDays: { type: Number, default: 0 },
    agingBucket: { type: String, default: 'lte30' },
    vendorCost: { type: Number, default: null },
    importBatchId: { type: String, default: '' },
    sourceFileName: { type: String, default: '' },
  },
  {
    collection: 'kehe_inventory',
    timestamps: true,
    autoIndex: false,
    strict: false,
  }
);

module.exports =
  mongoose.models.KeheInventory || mongoose.model('KeheInventory', inventorySchema);
